### ISSUE TITLE
Deprecated props & excessive CSS rules

### ISSUE THREAD

**Issue by r007** [timhagn/gatsby-background-image#22]
Hi @timhagn 

There are a couple props in your index.js
https://github.com/timhagn/gatsby-background-image/blob/e495fa6f17233b347abf6f30546cb2b560c18eeb/src/index.js#L346

```jsx
  style: PropTypes.object,
  imgStyle: PropTypes.object,
  placeholderStyle: PropTypes.object,
```
**PropTypes.object** is deprecated, please use **PropTypes.style** instead.

Also, there are many excessive CSS rules for every background. Here for example
https://github.com/timhagn/gatsby-background-image/blob/e495fa6f17233b347abf6f30546cb2b560c18eeb/src/StyleUtils.js#L68

```background-size``` is an old property which is widely supported by all modern browsers, no prefixes are needed. ```transition-delay``` - only -webkit prefix is needed. ```transition``` - only -webkit prefix is needed. So need to refactor CSS rule from this:

```css
.background-image {
  -webkit-background-size: ${backgroundSize};
  -moz-background-size: ${backgroundSize};
  -o-background-size: ${backgroundSize};
  background-size: ${backgroundSize};
  -webkit-transition-delay: ${transitionDelay};
  -moz-transition-delay: ${transitionDelay};
  -o-transition-delay: ${transitionDelay};
  transition-delay: ${transitionDelay};
  -webkit-transition: opacity 0.5s;
  -moz-transition: opacity 0.5s;
  -o-transition: opacity 0.5s;
  transition: opacity 0.5s;
}
```

to this:

```css
.background-image {
  background-size: ${backgroundSize};
  -webkit-transition-delay: ${transitionDelay};
  transition-delay: ${transitionDelay};
  -webkit-transition: opacity 0.5s;
  transition: opacity 0.5s;
}
```

Hope this helps.
