### ISSUE TITLE
Version 0.8.5 causes breaking changes to my CSS over 0.8.2

### ISSUE THREAD

**Issue by petercr** [timhagn/gatsby-background-image#67]
## Description

When I update to version 0.8.5 from version 0.8.2 it causes my CSS to go all out of whack 😮 
The best I can figure it seems that any `margin-top` or `padding-top` on the first child element get applied to the top of the Gatsby-background-image `div`. So even if I removed the `margin` and `padding` to the top of the element, it seems impossible to place the first child element relative to the containing `div` or `section`. 

The only fix I found was to roll it back to version 0.8.2

### Steps to reproduce

All I had to do was update my project from 0.8.2 to version 0.8.5. If you have a BitBucket account I can give you permission to take a look at all of the code. I'll post the CSS here and hopefully that will help. 

Here is a live version of the site [https://cranky-swartz-ab3d87.netlify.com/](https://cranky-swartz-ab3d87.netlify.com/)

```css
:root {
  --dark-purple: #4e2954;
  --light-purple: #910091;
}

body {
  margin: 0;
  padding: 0;
  scroll-snap-type: y proximity;
  scroll-padding: 10vh;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

.navbar {
  display: flex;
  align-items: center;
  align-content: center;
  justify-content: center;
  height: 10vh;
  position: fixed;
  width: 100%;
  top: 0;
  left: 0;
  z-index: 10;
}

.navbar-header {
  color: var(--dark-purple);
  text-decoration: none;
  padding-bottom: 4%;
}

.navbar-icon {
  padding-right: 18px;
  padding-top: 32%;
  z-index: 50 !important;
  position: absolute;
  width: 100%;
  display: flex;
  justify-content: flex-end;
}

.icon-bar {
  color: var(--light-purple);
}

/* Menu items CSS */

#menuBar {
  z-index: 50;
}

.menu-backdrop {
  position: fixed;
  width: 100vw;
  height: 90vh;
  left: 0px;
  top: 10vh;
  z-index: 5;
  background: rgba(0, 0, 0, 0.5);
}

.menu {
  position: fixed;
  width: 100%;
  height: 87%;
  left: 10%;
  top: 10%;
  display: flex;
  flex-direction: column;
  align-items: center;
  background: #ffffff;
  border: 3px solid var(--dark-purple);
  box-sizing: border-box;
  border-radius: 10px;
  z-index: 50;
  text-align: center;
}

.menu-items {
  color: var(--dark-purple);
  position: relative;
  width: 55%;
  z-index: 25;
  display: flex;
  flex-direction: column;
  justify-content: space-around;
  height: 60%;
  align-content: flex-end;
  align-items: flex-end;
  margin-top: 5%;
  font-size: 31px;
  /* line-height: 250%; */
  text-decoration: underline;
  list-style-type: none;
}

.menu-arrow {
  margin-right: 15px;
}

a .social-icon {
  margin-top: 47% !important;
  position: relative !important;
}

.service-menu {
  position: absolute;
  width: 38vw;
  max-width: 300px;
  height: 45vh;
  left: 15px;
  top: 18vh;
  background: #ffffff;
  border: 3px solid #4e2954;
  box-sizing: border-box;
  border-radius: 10px;
}

.service-menu > p {
  font-size: 28px;
  color: var(--dark-purple);
  text-decoration: underline;
}

.menu-social {
  display: grid;
  grid-template-columns: 1fr 1fr 1fr;
  width: 80%;
}

/* Landing Page CSS */

#landing {
  height: 100vh;
  scroll-snap-align: start;
}

#landing-text {
  color: black;
  position: absolute;
  top: 50vh;
  padding-left: 10%;
  padding-right: 10%;
  font-size: 32px;
  line-height: 150%;
  text-align: center;
}

/* Contact Page CSS */

#contact {
  height: 100vh;
  scroll-snap-align: start;
}

.contact-card {
  height: 60vh;
  width: 80%;
  margin-left: 10%;
  margin-top: 10vh;
  padding-bottom: 25px;
  background: linear-gradient(204.73deg, #754f9a 1.9%, #910091 98.67%);
  border-radius: 40px;
  color: #ffffff;
  position: relative;
  text-align: center;
  display: flex;
  flex-direction: column;
  justify-content: center;
}

.contact-list {
  list-style-type: none;
  font-size: 21px;
  padding-left: 0;
  height: 100%;
  justify-content: space-around;
  display: flex;
  flex-direction: column;
}

/* Service Page CSS */

#services {
  scroll-snap-align: start;
  display: flex;
  flex-direction: column;
  justify-content: space-evenly;
  align-items: center;
  flex-shrink: 1;
  margin: 0 0;
}

.services {
  display: grid;
  grid-template-columns: 1fr 1fr;
  width: 60%;
  text-align: center;
  line-height: 1;
  margin: 0;
}

.services-header {
  margin-top: 20px;
}

.services-wings {
  height: 100px;
  width: 100px;
  padding-top: 20px;
}

.wings-container {
  display: flex;
  flex-direction: row;
  width: 100%;
  max-width: 800px;
  justify-content: space-around;
}

/* About Page Stylings */
#about {
  height: 90vh;
  scroll-snap-align: start;
}

.about-h1 {
  color: var(--dark-purple);
  margin-top: 110px;
  font-size: 40px;
  padding-left: 25px;
  text-decoration: underline;
}

.about-text {
  color: white;
  margin-top: 150px;
  padding: 0 40px 0 20px;
  display: flex;
  align-items: center;
  font-size: 24px;
  text-shadow: 1px 1px 2px black;
}

```
### Expected result

Here is what it looks like with gatsby-backround-image v. 0.8.2
![How it should look](https://user-images.githubusercontent.com/26460352/63957551-9823ec00-ca56-11e9-9265-22781fa8fd2e.png)

![Doesn't look broken)](https://user-images.githubusercontent.com/26460352/63957575-a5d97180-ca56-11e9-8f8d-7aea21bb18de.png)

### Actual result

Here's how it looks with the margin and padding top's overflowing from the first child element of the background `div`

![Here is the div overflow](https://user-images.githubusercontent.com/26460352/63957911-521b5800-ca57-11e9-9f32-cdb7c9cda9e8.png)

![more of the overflow](https://user-images.githubusercontent.com/26460352/63957940-5e071a00-ca57-11e9-96da-cb4768a0c0b8.png)

### Environment

```bash

  System:
    OS: Windows 10
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
  Binaries:
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.11.2 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.16 - /c/Python27/python
  Browsers:
    Chrome Version 76.0.3809.132 (Official Build) (64-bit)
  npmPackages:
    gatsby: ^2.13.41 => 2.13.41 
    gatsby-background-image: ^0.8.5 => 0.8.5 
    gatsby-image: ^2.2.7 => 2.2.7 
    gatsby-plugin-google-analytics: ^2.1.4 => 2.1.4 
    gatsby-plugin-manifest: ^2.2.4 => 2.2.4 
    gatsby-plugin-offline: ^2.2.4 => 2.2.4 
    gatsby-plugin-prefetch-google-fonts: ^1.4.2 => 1.4.2 
    gatsby-plugin-react-helmet: ^3.1.0 => 3.1.2 
    gatsby-plugin-sharp: ^2.2.3 => 2.2.9 
    gatsby-plugin-sitemap: ^2.2.1 => 2.2.3 
    gatsby-plugin-styled-components: ^3.1.0 => 3.1.2 
    gatsby-source-filesystem: ^2.1.2 => 2.1.6 
    gatsby-transformer-sharp: ^2.2.1 => 2.2.4 

```
