### ISSUE TITLE
Passthrough does not work with responsive css

### ISSUE THREAD

**Issue by KB1RD** [timhagn/gatsby-background-image#71]
## Description

Hi, I encountered an issue the other day on iOS with fixed position images, so I decided to completely disable them on mobile for both performance and compatibility. To do this, I created a responsive CSS selector to set the background attachment to scroll by default and fixed on higher-res screens. This led to me encountering an issue where this plugin would not pass CSS `@media` queries on to the `::before` and `::after` selectors.

### Steps to reproduce
Create CSS like this:
```css
.bg-mobile-fixed-auto {
  background-attachment: scroll;
}
@screen md {
  .bg-mobile-fixed-auto {
    background-attachment: fixed;
  }
}
```
(`@screen` is the Tailwind CSS equivalent of `@media` and directly compiles into `@media`)

And HTML/JSX like this:
```html
    <BackgroundImage
      className="... bg-mobile-fixed-auto"
      fluid={...}
    />
```

### Expected result
`@media` queries should be transferred to CSS pseudoelements to allow responsive website design. In the case above, this would mean that the `BackgroundImage` would be scrolling on mobile and fixed on larger screens.

### Actual result
`@media` rules were not transferred to the CSS pseudoelements, so the image was not responsive. It was fixed on all screens. This is because the stylesheet that was generated was missing the `@media` rules. Here is what was on my webpage:
```css
          .w-full.h-half.relative.bg-mobile-fixed-auto.bg-cover.bg-center:before,
          .w-full.h-half.relative.bg-mobile-fixed-auto.bg-cover.bg-center:after {
            content: '';
            display: block;
            position: absolute;
            width: 100%;
            height: 100%;
            top: 0;
            left: 0;
            
            transition: opacity 0.5s ease 500ms;
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
            background-attachment: scroll;
            background-position-x: center;
            background-position-y: center;
          }
          .w-full.h-half.relative.bg-mobile-fixed-auto.bg-cover.bg-center:before {
            z-index: -100;
            background-image: url('http://localhost:8000/...');
            
            opacity: 1; 
          }
          .w-full.h-half.relative.bg-mobile-fixed-auto.bg-cover.bg-center:after {
            z-index: -101;
            
            background-image: url(data:image/jpeg;base64,...);
          }
```

I had a look at the [utils code](https://github.com/timhagn/gatsby-background-image/blob/master/packages/gatsby-background-image/src/BackgroundUtils.js) and, unfortunately, this does not appear to be a trivial fix. The style detector would have to be modified to detect `@media` queries. A possible workaround is to assign the `background-attachment` values to the `::before` and `::after` selectors, so this does not need to be *super* high on the priority list. Here's the workaround that I applied:
```css
.bg-mobile-fixed-auto,
.bg-mobile-fixed-auto::before,
.bg-mobile-fixed-auto::after {
  background-attachment: scroll;
}
@screen md {
  .bg-mobile-fixed-auto,
  .bg-mobile-fixed-auto::before,
  .bg-mobile-fixed-auto::after {
    background-attachment: fixed;
  }
}
```
Finally, I should note that this does *not* apply to any responsive code, just CSS that applies to the background. As seen in the Tailwind CSS issue that was opened, things like responsive width work fine.

### Environment

```
  System:
    OS: Linux
    CPU: Intel
    Shell: /bin/bash
  Binaries:
    Node: 10.11.0 - /usr/local/bin/node
    npm: 6.11.2 - /usr/local/bin/npm
  Languages:
    Python: 2.7.12 - /usr/bin/python
  Browsers:
  npmPackages:
    gatsby: 2.13.41 => 2.13.41
    gatsby-background-image-es5: ^0.8.2 => 0.8.2
    gatsby-image: ^2.2.7 => 2.2.7
    gatsby-plugin-postcss: 2.1.2 => 2.1.2
    gatsby-plugin-purgecss: 4.0.0 => 4.0.0
    gatsby-plugin-react-helmet: 3.1.2 => 3.1.2
    gatsby-plugin-sharp: ^2.2.9 => 2.2.9
    gatsby-source-directus7: ^0.8.1 => 0.8.1
    gatsby-source-filesystem: ^2.1.6 => 2.1.6
    gatsby-transformer-sharp: ^2.2.4 => 2.2.4
  npmGlobalPackages:
    gatsby-cli: 2.7.0
```
Also, thanks for all the hard work that you have put into this project. It looks like you're really busy rn so sorry to bother! :) I also typed this kind of quickly and while tired, so if I missed anything, feel free to let me know.
